export enum PROPERTIES_KEYS {
  CREATE_PROPERTY = 'CREATE_PROPERTY',
  UPDATE_PROPERTY = 'UPDATE_PROPERTY',
  ALL_PROPERTIES_BY_AGENCY = 'ALL_PROPERTIES_BY_AGENCY',
  ALL_PROPERTIES_PUBLIC = 'ALL_PROPERTIES_PUBLIC',
  OCCUPATION_RATE_BY_PROPERTY_TYPE = 'OCCUPATION_RATE_BY_PROPERTY_TYPE',
  MONTHLY_REVENUE = 'MONTHLY_REVENUE',
}
