export enum NOTIFICATIONS_KEYS {
  GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS',
  GET_ALL_UNREAD_NOTIFICATION = 'GET_ALL_UNREAD_NOTIFICATION',
  READ_ALL_NOTIFICATION = 'READ_ALL_NOTIFICATION',
  READ_ONE_NOTIFICATION = 'READ_ONE_NOTIFICATION',
}
