export enum Status {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PENDING = "PENDING",
  INFO = "INFO",
  WARNING = "WARNING",
  PAYMENT = "PAYMENT",
  CLOSE = "CLOSE",
  OPEN = "OPEN",
  AVAILABLE = "AVAILABLE",
  RESERVED = "RESERVED",
  RENTED = "RENTED",
}
