export enum LandPaymentType {
  CASH = 'CASH',
  PARTIAL = 'PARTIAL',
}

export enum PropertyType {
  APARTMENT = 'APARTMENT',
  HOUSE = 'HOUSE',
  STUDIO = 'STUDIO',
}

export enum PlanType {
  BASIC_COMMISSION = 'BASIC_COMMISSION',
  STANDARD_COMMISSION = 'STANDARD_COMMISSION',
  PREMIUM_COMMISSION = 'PREMIUM_COMMISSION',
  BASIC_SUB = 'BASIC_SUB',
  STANDARD_SUB = 'STANDARD_SUB',
  PREMIUM_SUB = 'PREMIUM_SUB',
}

export type PlanCategory = 'COMMISSION_BASED' | 'SUBSCRIPTION_BASED';
export type PricingType = 'COMMISSION' | 'SUBSCRIPTION';
export type BillingCycle = 'MONTHLY' | 'YEARLY';
export type PlanTier = 'BASIC' | 'STANDARD' | 'PREMIUM';

export enum UserRole {
  OWNER = 'OWNER', // propriétaire de l'agence,
  AGENT = 'AGENT', // agent interne agence
}

export enum AgencyRole {
  AGENT = 'AGENT',
}

export enum NotificationType {
  MESSAGE = 'MESSAGE',
  PAYMENT = 'PAYMENT',
  MAINTENANCE = 'MAINTENANCE',
  SYSTEM = 'SYSTEM',
  LEAD = 'LEAD',
  VISIT = 'VISIT',
  TICKET = 'TICKET',
}
export enum PropertyFeature {
  KITCHEN = 'KITCHEN',
  LIVING_ROOM = 'LIVING_ROOM',
  DINING_ROOM = 'DINING_ROOM',
  OFFICE = 'OFFICE',
  BASEMENT = 'BASEMENT',
  ATTIC = 'ATTIC',
  STORAGE_ROOM = 'STORAGE_ROOM',
  GARDEN = 'GARDEN',
  TERRACE = 'TERRACE',
  BALCONY = 'BALCONY',
  COURTYARD = 'COURTYARD',
  POOL = 'POOL',
  GARAGE = 'GARAGE',
  PARKING = 'PARKING',
  FURNISHED = 'FURNISHED',
  PARTIALLY_FURNISHED = 'PARTIALLY_FURNISHED',
  AIR_CONDITIONING = 'AIR_CONDITIONING',
  HEATING = 'HEATING',
  FIREPLACE = 'FIREPLACE',
  ELEVATOR = 'ELEVATOR',
  INTERCOM = 'INTERCOM',
  ALARM_SYSTEM = 'ALARM_SYSTEM',
  DIGICODE = 'DIGICODE',
  BILLS_INCLUDED = 'BILLS_INCLUDED',
  WATER_INCLUDED = 'WATER_INCLUDED',
  ELECTRICITY_INCLUDED = 'ELECTRICITY_INCLUDED',
  GAS_INCLUDED = 'GAS_INCLUDED',
  INTERNET_INCLUDED = 'INTERNET_INCLUDED',
  CABLE_TV_INCLUDED = 'CABLE_TV_INCLUDED',
  CLEANING_INCLUDED = 'CLEANING_INCLUDED',
  PETS_ALLOWED = 'PETS_ALLOWED',
  SMOKING_ALLOWED = 'SMOKING_ALLOWED',
  WHEELCHAIR_ACCESSIBLE = 'WHEELCHAIR_ACCESSIBLE',
  CONCIERGE = 'CONCIERGE',
  WASHING_MACHINE = 'WASHING_MACHINE',
  DRYER = 'DRYER',
  DISHWASHER = 'DISHWASHER',
  REFRIGERATOR = 'REFRIGERATOR',
  OVEN = 'OVEN',
  MICROWAVE = 'MICROWAVE',
  TV = 'TV',
  BBQGRILL = 'BBQGRILL',
}
