import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import "react-day-picker/dist/style.css";
import "react-international-phone/style.css";
import "_components/custom/agenda/index.css";
import GlobalApplicationProvider from "_context/provider/GlobalApplicationProvider";
import { ThemeProvider } from "_components/ui/provider";
import { LoaderProvider } from "_context/loaderContext";
import { Toaster } from "_components/ui/toaster";
import { I18nProvider } from "_context/provider/i18n-provider";
import { AuthContextProvider } from "_context/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalApplicationProvider>
          <ThemeProvider>
            <LoaderProvider>
              <Toaster />
              <AuthContextProvider>
                <I18nProvider>{children}</I18nProvider>
              </AuthContextProvider>
            </LoaderProvider>
          </ThemeProvider>
        </GlobalApplicationProvider>
      </body>
    </html>
  );
}
