export enum INVITE_KEYS {
  CREATE_INVITATION = "CREATE_INVITATION",
  ACCEPT_INVITATION = "ACCEPT_INVITATION",
  CANCEL_INVITATION = "CANCEL_INVITATION",
  INVITATION_AGENCY_LIST = "INVITATION_AGENCY_LIST",
}
