export enum LEAD_KEYS {
  CREATE_LEADS = 'CREATE_LEADS',
  ASSIGN_LEADS = 'ASSIGN_LEADS',
  DELETE_LEADS = 'DELETE_LEADS',
  AGENCY_LEADS_LIST = 'AGENCY_LEADS_LIST',
  USER_LEADS_LIST = 'USER_LEADS_LIST',
}
