export enum INTEGRATIONS_KEYS {
  GET_URL = 'GET_URL',
  GET_FILES = 'GET_FILES',
  DISCONNECT_PROVIDER = 'DISCONNECT_PROVIDER',
  UPLOAD_FILE = 'UPLOAD_FILE',
  GET_PROVIDER_STATUS = 'GET_PROVIDER_STATUS',
  GET_TRASHED_FILES = 'GET_TRASHED_FILES',
  TRASHED_FILE = 'TRASHED_FILE',
  DELETE_FILE = 'DELETE_FILE',
}
