export enum CONTACT_KEYS {
  PUBLIC_CONTACT_REQUEST = 'PUBLIC_CONTACT_REQUEST',
  AGENCY_CONTACT_LIST = 'AGENCY_CONTACT_LIST',
  AGENCY_CONTACT_UPDATE_STATUS = 'AGENCY_CONTACT_UPDATE_STATUS',
  AGENCY_CONTACT_READ_ALL = 'AGENCY_CONTACT_READ_ALL',
}
