export enum CONTACT_KEYS {
  PUBLIC_REQUEST = "PUBLIC_REQUEST",
  AGENCY_REQUEST_LIST = "AGENCY_REQUEST_LIST",
  CHANGE_REQUEST_STATUS = "CHANGE_REQUEST_STATUS",
  READ_ALL_REQUESTS = "READ_ALL_REQUESTS",
}
